# Generated by Django 5.1.1 on 2024-09-05 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="description",
            new_name="department",
        ),
    ]
